MolinaTextileSystemDemo/MolinaTextileSystem/Controllers/CustomerOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MolinaTextileSystem.Models;
using MolinaTextileSystem.Repositories.CustomerOrders;
using MolinaTextileSystem.Repositories.CustomersOrdersDetails;

namespace MolinaTextileSystem.Controllers
{
    [Authorize]
    public class CustomerOrderController : Controller
    {
        private readonly ICustomerOrderRepository _customerOrderRepository;
        private readonly ICustomersOrdersDetailsRepository _customersOrdersDetailsRepository;

        private SelectList _customersList;
        private SelectList _employeesList;
        private SelectList _statesList;

        public CustomerOrderController(ICustomerOrderRepository customerOrderRepository, ICustomersOrdersDetailsRepository customersOrdersDetailsRepository)
        {
            _customerOrderRepository = customerOrderRepository;
            _customersOrdersDetailsRepository = customersOrdersDetailsRepository;
            _customersList = new SelectList(
                _customerOrderRepository.GetAllCustomers(),
                nameof(CustomerModel.CustomerId),
                nameof(CustomerModel.CustomerName)
            );
            _employeesList = new SelectList(
                _customerOrderRepository.GetAllEmployees(),
                nameof(EmployeeModel.EmployeeId),
                nameof(EmployeeModel.EmployeeName)
            );
            _statesList = new SelectList(
                _customerOrderRepository.GetAllStates(),
                nameof(StateModel.StateId),
                nameof(StateModel.StateName)
            );
        }

        // GET: CustomerOrderController
        public ActionResult Index()
        {
            return View(_customerOrderRepository.GetAll());
        }

        public ActionResult GetAllCustomerOrderDetails(int id)
        {
            ViewBag.CustomerOrderId = id;
            return View(_customersOrdersDetailsRepository.GetSpecificById(id));
        }

        // GET: CustomerOrderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CustomerOrderController/Create
        public ActionResult Create()
        {
            ViewBag.Customers = _customersList;
            ViewBag.Employees = _employeesList;
            ViewBag.States = _statesList;

            return View();
        }

        // POST: CustomerOrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerOrderModel customerOrder)
        {
            try
            {
                int id = _customerOrderRepository.Add(customerOrder);

                TempData["message"] = "Datos guardados correctamente.";

                return RedirectToAction("GetAllCustomerOrderDetails", new { id });
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                ViewBag.Customers = _customersList;
                ViewBag.Employees = _employeesList;
                ViewBag.States = _statesList;

                return View(customerOrder);
            }
        }

        // GET: CustomerOrderController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var customerOrder = _customerOrderRepository.GetById(id);

            if (customerOrder == null)
            {
                return NotFound();
            }

            _customersList = new SelectList(
                _customerOrderRepository.GetAllCustomers(),
                nameof(CustomerModel.CustomerId),
                nameof(CustomerModel.CustomerName),
                customerOrder?.Customer?.CustomerId
            );
            _employeesList = new SelectList(
                _customerOrderRepository.GetAllEmployees(),
                nameof(EmployeeModel.EmployeeId),
                nameof(EmployeeModel.EmployeeName),
                customerOrder?.Employee?.EmployeeId
            );
            _statesList = new SelectList(
                _customerOrderRepository.GetAllStates(),
                nameof(StateModel.StateId),
                nameof(StateModel.StateName),
                customerOrder?.State?.StateId
            );

            ViewBag.Customers = _customersList;
            ViewBag.Employees = _employeesList;
            ViewBag.States = _statesList;

            return View(customerOrder);
        }

        // POST: CustomerOrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerOrderModel customerOrder)
        {
            try
            {
                _customerOrderRepository.Edit(customerOrder);

                TempData["message"] = "Datos editados correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                ViewBag.Customers = _customersList;
                ViewBag.Employees = _employeesList;
                ViewBag.States = _statesList;

                return View(customerOrder);
            }
        }

        // GET: CustomerOrderController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var customerOrder = _customerOrderRepository.GetById(id);

            if (customerOrder == null)
            {
                return NotFound();
            }

            return View(customerOrder);
        }

        // POST: CustomerOrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CustomerOrderModel customerOrder)
        {
            try
            {
                _customerOrderRepository.Delete(customerOrder.CustomerOrderId);

                TempData["message"] = "Dato eliminado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(customerOrder);
            }
        }
    }
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/CustomerOrder/Create.cshtml
@model CustomerOrderModel

@{
    ViewData["Title"] = "Creación orden de cliente";
}

<h1 style="text-align:center">Creación orden de cliente</h1>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" onsubmit="return confirmAction();">
                @Html.AntiForgeryToken()
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="mb-3">
                    <label asp-for="EmployeeId" class="form-label">Empleado</label>
                    <select asp-for="EmployeeId"
                            asp-items="@ViewBag.Employees"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="EmployeeId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CustomerId" class="form-label">Cliente</label>
                    <select asp-for="CustomerId"
                            asp-items="@ViewBag.Customers"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="CustomerId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CreationDate" class="form-label">Fecha de la orden</label>
                    <input asp-for="CreationDate" type="date" class="form-control" />
                    <span asp-validation-for="CreationDate" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="DeliveryDate" class="form-label">Fecha de la entrega</label>
                    <input asp-for="DeliveryDate" type="date" class="form-control" />
                    <span asp-validation-for="DeliveryDate" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="TotalAmount" class="form-label">Total</label>
                    <input asp-for="TotalAmount" type="number" class="form-control" />
                    <span asp-validation-for="TotalAmount" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="StateId" class="form-label">Estado</label>
                    <select asp-for="StateId"
                            asp-items="@ViewBag.States"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="StateId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />

                    <a asp-action="Index" class="btn btn-danger">Regresar al listado</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function confirmAction() {
            if (confirm('¿Estás seguro de agregar esta orden?')) {
                return true;
            } else {
                window.location.href = '@Url.Action("Index", "CustomerOrder")';
                return false;
            }
        }
    </script>
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/CustomerOrder/Delete.cshtml
@model CustomerOrderModel

@{
    ViewData["Title"] = "Eliminar orden";
}

<div style="text-align: center;">
    <h1>Eliminar orden</h1>
    <h3>¿Está seguro que desea eliminar?</h3>

    <div style="margin: 0 auto; width: fit-content;">
        <table style="text-align: justify; border-collapse: separate; border-spacing: 0 8px;">
            <tbody>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.CustomerOrderId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.CustomerOrderId)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.EmployeeId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.EmployeeId)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.CustomerId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.CustomerId)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.CreationDate)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.CreationDate)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.DeliveryDate)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.DeliveryDate)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.TotalAmount)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.TotalAmount)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.StateId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.StateId)
                    </td>
                </tr>
            </tbody>
        </table>

        <form asp-action="Delete">
            <input asp-for="CustomerOrderId" type="hidden" class="form-control" />
            <input type="submit" value="Eliminar" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-primary">Regresar al listado</a>
        </form>
    </div>
</div>

MolinaTextileSystemDemo/MolinaTextileSystem/Views/CustomerOrder/Edit.cshtml
@model CustomerOrderModel

@{
    ViewData["Title"] = "Creación orden de cliente";
}

<h1 style="text-align:center">Creación orden de cliente</h1>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Edit" onsubmit="return confirmAction();">
                @Html.AntiForgeryToken()
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="mb-3">
                    <input asp-for="CustomerOrderId" type="hidden" class="form-control" />
                </div>
                <div class="mb-3">
                    <label asp-for="EmployeeId" class="form-label">Empleado</label>
                    <select asp-for="EmployeeId"
                            asp-items="@ViewBag.Employees"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="EmployeeId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CustomerId" class="form-label">Cliente</label>
                    <select asp-for="CustomerId"
                            asp-items="@ViewBag.Customers"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="CustomerId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CreationDate" class="form-label">Fecha de la orden</label>
                    <input asp-for="CreationDate" type="date" class="form-control" />
                    <span asp-validation-for="CreationDate" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="DeliveryDate" class="form-label">Fecha de la entrega</label>
                    <input asp-for="DeliveryDate" type="date" class="form-control" />
                    <span asp-validation-for="DeliveryDate" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="TotalAmount" class="form-label">Total</label>
                    <input asp-for="TotalAmount" type="number" class="form-control" />
                    <span asp-validation-for="TotalAmount" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="StateId" class="form-label">Estado</label>
                    <select asp-for="StateId"
                            asp-items="@ViewBag.States"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="StateId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />

                    <a asp-action="Index" class="btn btn-danger">Regresar al listado</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function confirmAction() {
            if (confirm('¿Estás seguro de editar esta orden?')) {
                return true;
            } else {
                window.location.href = '@Url.Action("Index", "CustomerOrder")';
                return false;
            }
        }
    </script>
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/CustomerOrder/GetAllCustomerOrderDetails.cshtml
@model IEnumerable<MolinaTextileSystem.Models.CustomerOrderDetailModel>

@{
    ViewData["Title"] = "Detalles de la Orden del Cliente";
}

<h1 style="text-align:center">Añadir detalle a esta orden</h1>


<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="mb-3 mb-3">
                <a asp-action="Create" asp-controller="CustomerOrderDetail" asp-route-id="@ViewBag.CustomerOrderId" class="btn btn-success">
                    Añadir detalle a la orden
                </a>
            </div>

            @if (TempData["message"] != null)
            {
                <div class="alert alert-primary" role="alert">
                    @TempData["message"]
                </div>
            }

            <table class="table table-bordered table-striped table-responsive" id="customerOrderDetailTable">
                <thead>
                    <tr>
                        <td>Orden de cliente</td>
                        <td>Detalle</td>
                        <td>Producto</td>
                        <td>Precio unitario</td>
                        <td>Cantidad</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var customerOrderDetail in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(item => customerOrderDetail.CustomerOrderId)</td>
                            <td>@Html.DisplayFor(item => customerOrderDetail.CustomerOrderDetailId)</td>
                            <td>@customerOrderDetail.Producto?.ProductName</td>
                            <td>@Html.DisplayFor(item => customerOrderDetail.UnitPrice)</td>
                            <td>@Html.DisplayFor(item => customerOrderDetail.CustomerOrderDetailQuantity)</td>
                            <td>
                                <a asp-controller="CustomerOrderDetail"
                                   asp-action="Edit"
                                   asp-route-id="@customerOrderDetail.CustomerOrderDetailId"
                                   asp-route-id="@ViewBag.CustomerOrderId"
                                   class="btn btn-primary">
                                    Editar
                                </a>
                                <a asp-controller="CustomerOrderDetail"
                                   asp-action="Delete"
                                   asp-route-id="@customerOrderDetail.CustomerOrderDetailId"
                                   asp-route-id="@ViewBag.CustomerOrderId"
                                   class="btn btn-danger">
                                    Eliminar
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
<script>
    $(document).ready(function () {
        $("#customerOrderDetailTable").DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'csv',
                    exportOptions: {
                        columns: ':not(:last-child)'
                    }
                },
                {
                    extend: 'pdf',
                    exportOptions: {
                        columns: ':not(:last-child)'
                    }
                },
                {
                    extend: 'excel',
                    exportOptions: {
                        columns: ':not(:last-child)'
                    }
                }
            ],
            columnDefs: [
                {
                    targets: 5,
                    orderable: false,
                    searchable: false
                }
            ],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json'
            }
        });
    });
</script>
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/CustomerOrder/Index.cshtml
@model IEnumerable<CustomerOrderModel>
@{
	ViewData["Title"] = "Ordenes de clientes";
}

<h1 style="text-align:center">Ordenes de clientes</h1>

<div class="container">
	<div class="row">
		<div class="col-md-12">

			<div class="mb-3 mb-3">
				<a asp-action="Create" asp-controller="CustomerOrder" class="btn btn-success">
					Nueva orden
				</a>
			</div>

			@if (TempData["message"] != null)
			{
				<div class="alert alert-primary" role="alert">
					@TempData["message"]
				</div>
			}

			<table class="table table-bordered table-striped table-responsive" id="customerOrderTable">
				<thead>
					<tr>
						<td>Orden ID</td>
						<td>Empleado</td>
						<td>Cliente</td>
						<td>Fecha de la orden</td>
						<td>Fecha de la entrega</td>
						<td>Total</td>
						<td>Estado</td>
						<td>Detalles</td>
						<td>Acciones</td>
					</tr>
				</thead>
				<tbody>
					@foreach (var customerOrderModel in Model)
					{
						<tr>
							<td>@Html.DisplayFor(item => customerOrderModel.CustomerOrderId)</td>
							<td>@customerOrderModel.Employee?.EmployeeName</td>
							<td>@customerOrderModel.Customer?.CustomerName</td>
							<td>@Html.DisplayFor(item => customerOrderModel.CreationDate)</td>
							<td>@Html.DisplayFor(item => customerOrderModel.DeliveryDate)</td>
							<td>@Html.DisplayFor(item => customerOrderModel.TotalAmount)</td>
							<td>@customerOrderModel.State?.StateName</td>
							<td>
								<a asp-controller="CustomerOrder"
								   asp-action="GetAllCustomerOrderDetails"
								   asp-route-id="@customerOrderModel.CustomerOrderId"
								   class="btn btn-primary">
									Detalles
								</a>
							</td>
							<td>
								<a asp-controller="CustomerOrder"
								   asp-action="Edit"
								   asp-route-id="@customerOrderModel.CustomerOrderId"
								   class="btn btn-primary">
									Editar
								</a>
								<a asp-controller="CustomerOrder"
								   asp-action="Delete"
								   asp-route-id="@customerOrderModel.CustomerOrderId"
								   class="btn btn-danger">
									Eliminar
								</a>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>

@section Scripts {
	<script>
		$(document).ready(function () {
			$("#customerOrderTable").DataTable({
				dom: 'Bfrtip',
				buttons: [
					{
						extend: 'csv',
						exportOptions: {
							columns: [0, 1, 2, 3, 4, 5, 6]
						}
					},
					{
						extend: 'pdf',
						exportOptions: {
							columns: [0, 1, 2, 3, 4, 5, 6]
						}
					},
					{
						extend: 'excel',
						exportOptions: {
							columns: [0, 1, 2, 3, 4, 5, 6]
						}
					}
				],
				columns: [
					null,
					null,
					null,
					null,
					null,
					null,
					null,
					{ orderable: false, searchable: false },
					{ orderable: false, searchable: false }
				],
				language: {
					url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json'
				}
			});
		});
	</script>
}