MolinaTextileSystemDemo/MolinaTextileSystem/Controllers/PatternController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MolinaTextileSystem.Models;
using MolinaTextileSystem.Repositories.Pattern;

namespace MolinaTextileSystem.Controllers
{
    [Authorize]
    public class PatternController : Controller
    {
        private readonly IPatternRepository _patternRepository;


        public PatternController(IPatternRepository patternRepository)
        {
            _patternRepository = patternRepository;

        }

        public ActionResult Index()
        {
            return View(_patternRepository.GetAll());
        }

        // GET: CustomersController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CustomersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatternModel pattern)
        {
            try
            {
                _patternRepository.Add(pattern);

                TempData["createpattern"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(pattern);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var pattern = _patternRepository.GetById(id);

            if (pattern == null)
            {
                return NotFound();
            }

            return View(pattern);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PatternModel pattern)
        {
            try
            {
                _patternRepository.Edit(pattern);

                TempData["editpattern"] = "Datos editados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(pattern);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var pattern = _patternRepository.GetById(id);

            if (pattern == null)
            {
                return NotFound();
            }

            return View(pattern);
        }

        // POST: SuppliersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(PatternModel pattern)
        {
            try
            {
                _patternRepository.Delete(pattern.PatternId);

                TempData["deletecustomers"] = "Dato eliminados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(pattern);
            }
        }
    }
}

MolinaTextileSystemDemo/MolinaTextileSystem/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MolinaTextileSystem.Models;
using MolinaTextileSystem.Repositories.Products;

namespace MolinaTextileSystem.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;

        private SelectList _patternList;
        private SelectList _stateList;

        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
            _patternList = new SelectList(
                _productRepository.GetAllPattern(),
                nameof(PatternModel.PatternId),
                nameof(PatternModel.PatternName)
            );

            _stateList = new SelectList(
                _productRepository.GetAllState(),
                nameof(StateModel.StateId),
                nameof(StateModel.StateName)
            );
        }

        // GET: ProductController
        public ActionResult Index()
        {
            return View(_productRepository.GetAll());
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            ViewBag.Pattern = _patternList;
            ViewBag.State = _stateList;

            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductModel product)
        {
            try
            {
                _productRepository.Add(product);

                TempData["message"] = "Datos guardados correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                ViewBag.Pattern = _patternList;
                ViewBag.State = _stateList;

                return View(product);
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _productRepository.GetById(id);

            if (product == null)
            {
                return NotFound();
            }

            _patternList = new SelectList(
                _productRepository.GetAllPattern(),
                nameof(PatternModel.PatternId),
                nameof(PatternModel.PatternName),
                product?.Pattern?.PatternId
            );

            _stateList = new SelectList(
                _productRepository.GetAllState(),
                nameof(StateModel.StateId),
                nameof(StateModel.StateName),
                product?.States?.StateId
            );

            ViewBag.Pattern = _patternList;
            ViewBag.State = _stateList;

            return View(product);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductModel product)
        {
            try
            {
                _productRepository.Edit(product);

                TempData["message"] = "Datos editados correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                ViewBag.Pattern = _patternList;
                ViewBag.State = _stateList;

                return View(product);
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            var product = _productRepository.GetById(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ProductModel product)
        {
            try
            {
                _productRepository.Delete(product.ProductId);

                TempData["message"] = "Dato eliminado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(product);
            }
        }
    }
}

MolinaTextileSystemDemo/MolinaTextileSystem/Controllers/StateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MolinaTextileSystem.Models;
using MolinaTextileSystem.Repositories.Estado;

namespace MolinaTextileSystem.Controllers
{
    [Authorize]
    public class StateController : Controller
    {
        private readonly IStateRepository _stateRepository;

        public StateController(IStateRepository stateRepository)
        {
            _stateRepository = stateRepository;
        }

        public ActionResult Index()
        {
            return View(_stateRepository.GetAll());
        }

        // GET: StateController/Details/5
        public ActionResult Details(int id)
        {
            var state = _stateRepository.GetById(id);

            if (state == null)
            {
                return NotFound();
            }

            return View(state);
        }

        // GET: StateController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StateController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StateModel state)
        {
            try
            {
                _stateRepository.Add(state);

                TempData["createstate"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(state);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var state = _stateRepository.GetById(id);

            if (state == null)
            {
                return NotFound();
            }

            return View(state);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StateModel state)
        {
            try
            {
                _stateRepository.Edit(state);

                TempData["editstate"] = "Datos editados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(state);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var state = _stateRepository.GetById(id);

            if (state == null)
            {
                return NotFound();
            }

            return View(state);
        }

        // POST: StateController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(StateModel state)
        {
            try
            {
                _stateRepository.Delete(state.StateId);

                TempData["deletestate"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(state);
            }
        }

    }
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MolinaTextileSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/MolinaTextileSystem.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/1.13.8/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-action="Index" asp-controller="Home">Sistema Molina Textil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark">Inicio</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Catálogo
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="CustomerOrder">Crear orden</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="">Credenciales de empleados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Customer">Clientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Employee">Empleados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Supplier">Proveedores</a>
                                </li>
                                @if (TempData["RolUsername"]?.ToString() == EnumRolesModel.RolUsuario.Administrador.ToString())
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="LoginCredential">Credenciales de empleados</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="State">Estados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Product">Productos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="CustomerOrderDetail">Detalles de Ordenes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="PatternDetail">Detalles de Patrones</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Pattern">Patrones</a>
                                </li>                                
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Category">Categorias</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="RawMaterials">Materiales</a>
                                </li>

                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark logout-link" asp-controller="LoginCredential" asp-action="Logout">Cerrar sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sistema Molina Textil - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>