MolinaTextileSystemDemo/MolinaTextileSystem/Controllers/PatternDetailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MolinaTextileSystem.Models;
using MolinaTextileSystem.Repositories.CustomersOrdersDetails;
using MolinaTextileSystem.Repositories.PatternDetails;

namespace MolinaTextileSystem.Controllers
{
    [Authorize]
    public class PatternDetailController : Controller
	{
		public readonly IPatternDetailRepository _patternDetailRepository;

		private SelectList _rawMaterialList;
		private SelectList _patternList;

		public PatternDetailController(IPatternDetailRepository patternDetailRepository)
		{
			_patternDetailRepository = patternDetailRepository;

			_rawMaterialList = new SelectList(
				_patternDetailRepository.GetAllRawMaterials(),
				nameof(RawMaterialsModel.RawMaterialId),
				nameof(RawMaterialsModel.RawMaterialName)
			);
			_patternList = new SelectList(
				_patternDetailRepository.GetAllPatterns(),
				nameof(PatternModel.PatternId),
				nameof(PatternModel.PatternName)
			);
		}

		// GET: PatternDetailController
		public ActionResult Index()
		{
			return View(_patternDetailRepository.GetAll());
		}

		// GET: PatternDetailController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: PatternDetailController/Create
		public ActionResult Create()
		{
			ViewBag.RawMaterials = _rawMaterialList;
			ViewBag.Patterns = _patternList;

			return View();
		}

		// POST: PatternDetailController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(PatternDetailModel patternDetail)
		{
			try
			{
				_patternDetailRepository.Add(patternDetail);

				TempData["message"] = "Datos guardados correctamente.";

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				TempData["message"] = ex.Message;

				ViewBag.RawMaterials = _rawMaterialList;
				ViewBag.Patterns = _patternList;

				return View(patternDetail);
			}
		}

		// GET: PatternDetailController/Edit/5
		[HttpGet]
		public ActionResult Edit(int id)
		{
			var patternDetail = _patternDetailRepository.GetById(id);

			if (patternDetail == null)
			{
				return NotFound();
			}

			_rawMaterialList = new SelectList(
				_patternDetailRepository.GetAllRawMaterials(),
				nameof(RawMaterialsModel.RawMaterialId),
				nameof(RawMaterialsModel.RawMaterialName),
				patternDetail?.RawMaterial?.RawMaterialId
			);
			_patternList = new SelectList(
				_patternDetailRepository.GetAllPatterns(),
				nameof(PatternModel.PatternId),
				nameof(PatternModel.PatternName),
				patternDetail?.Pattern?.PatternId
			);

			ViewBag.RawMaterials = _rawMaterialList;
			ViewBag.Patterns = _patternList;

			return View(patternDetail);
		}

		// POST: PatternDetailController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(PatternDetailModel patternDetail)
		{
			try
			{
				_patternDetailRepository.Edit(patternDetail);

				TempData["message"] = "Datos editados correctamente.";

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				TempData["message"] = ex.Message;

				ViewBag.RawMaterials = _rawMaterialList;
				ViewBag.Patterns = _patternList;

				return View(patternDetail);
			}
		}

		// GET: PatternDetailController/Delete/5
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var patternDetail = _patternDetailRepository.GetById(id);

			if (patternDetail == null)
			{
				return NotFound();
			}

			return View(patternDetail);
		}

		// POST: PatternDetailController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(PatternDetailModel patternDetail)
		{
			try
			{
				_patternDetailRepository.Delete(patternDetail.PatternDetailId);

				TempData["message"] = "Dato eliminado correctamente.";

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				TempData["message"] = ex.Message;

				return View(patternDetail);
			}
		}
	}
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/PatternDetail/Create.cshtml
@model PatternDetailModel

@{
    ViewData["Title"] = "Creación de detalle";
}

<h1 style="text-align:center">Creación de detalle</h1>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" onsubmit="return confirmAction();">
                @Html.AntiForgeryToken()
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="mb-3">
                    <label asp-for="RawMaterialId" class="form-label">Materia prima</label>
                    <select asp-for="RawMaterialId"
                            asp-items="@ViewBag.RawMaterials"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="RawMaterialId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="RawMaterialQuantity" class="form-label">Cantidad de material</label>
                    <input asp-for="RawMaterialQuantity" type="number" class="form-control" />
                    <span asp-validation-for="RawMaterialQuantity" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PatternId" class="form-label">Patrón</label>
                    <select asp-for="PatternId"
                            asp-items="@ViewBag.Patterns"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="PatternId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />

                    <a asp-action="Index" class="btn btn-danger">Regresar al listado</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function confirmAction() {
            if (confirm('¿Estás seguro de agregar este detalle?')) {
                return true;
            } else {
                window.location.href = '@Url.Action("Index", "PatternDetail")';
                return false;
            }
        }
    </script>
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/PatternDetail/Delete.cshtml
@model PatternDetailModel

@{
    ViewData["Title"] = "Eliminar detalle";
}

<div style="text-align: center;">
    <h1>Eliminar orden</h1>
    <h3>¿Está seguro que desea eliminar?</h3>

    <div style="margin: 0 auto; width: fit-content;">
        <table style="text-align: justify; border-collapse: separate; border-spacing: 0 8px;">
            <tbody>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.RawMaterialId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.RawMaterialId)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.RawMaterialId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.RawMaterialId)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.RawMaterialQuantity)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.RawMaterialQuantity)
                    </td>
                </tr>
                <tr>
                    <th style="padding-bottom: 8px;">
                        @Html.DisplayNameFor(model => model.PatternId)
                    </th>
                    <td style="padding: 0px 0px 8px 10px;">
                        @Html.DisplayFor(model => model.PatternId)
                    </td>
                </tr>
            </tbody>
        </table>

        <form asp-action="Delete">
            <input asp-for="PatternDetailId" type="hidden" class="form-control" />
            <input type="submit" value="Eliminar" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-primary">Regresar al listado</a>
        </form>
    </div>
</div>

MolinaTextileSystemDemo/MolinaTextileSystem/Views/PatternDetail/Edit.cshtml
@model PatternDetailModel

@{
    ViewData["Title"] = "Edición de detalle";
}

<h1 style="text-align:center">Edición de detalle</h1>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Edit" onsubmit="return confirmAction();">
                @Html.AntiForgeryToken()
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="mb-3">
                    <input asp-for="PatternDetailId" type="hidden" class="form-control" />
                </div>
                <div class="mb-3">
                    <label asp-for="RawMaterialId" class="form-label">Materia prima</label>
                    <select asp-for="RawMaterialId"
                            asp-items="@ViewBag.RawMaterials"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="RawMaterialId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="RawMaterialQuantity" class="form-label">Cantidad de material</label>
                    <input asp-for="RawMaterialQuantity" type="number" class="form-control" />
                    <span asp-validation-for="RawMaterialQuantity" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PatternId" class="form-label">Patrón</label>
                    <select asp-for="PatternId"
                            asp-items="@ViewBag.Patterns"
                            class="form-select">
                        <option value="">Seleccione</option>
                    </select>
                    <span asp-validation-for="PatternId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar" class="btn btn-primary" />

                    <a asp-action="Index" class="btn btn-danger">Regresar al listado</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function confirmAction() {
            if (confirm('¿Estás seguro de editar este detalle?')) {
                return true;
            } else {
                window.location.href = '@Url.Action("Index", "PatternDetail")';
                return false;
            }
        }
    </script>
}

MolinaTextileSystemDemo/MolinaTextileSystem/Views/PatternDetail/Index.cshtml
@model IEnumerable<PatternDetailModel>
@{
    ViewData["Title"] = "Detalles de patrones";
}

<h1 style="text-align:center">Detalles de patrones</h1>

<div class="container">
    <div class="row d-flex">
        <div class="col-6">
            <div class="mb-3">
                <a asp-action="Create" asp-controller="PatternDetail" class="btn btn-success">
                    Nuevo detalle de patrón
                </a>
            </div>
        </div>
    </div>

    @if (TempData["message"] != null)
    {
        <div class="alert alert-primary" role="alert">
            @TempData["message"]
        </div>
    }

    <table class="table table-bordered table-striped table-responsive" id="patternDetail">
        <thead>
            <tr>
                <td>Detalle de patrón ID</td>
                <td>Materia prima</td>
                <td>Cantidad de materia prima</td>
                <td>Patrón</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var patternDetail in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(item => patternDetail.PatternDetailId)</td>
                    <td>@patternDetail.RawMaterial?.RawMaterialName</td>
                    <td>@Html.DisplayFor(item => patternDetail.RawMaterialQuantity)</td>
                    <td>@patternDetail.Pattern?.PatternName</td>
                    <td>
                        <a asp-controller="PatternDetail" asp-action="Edit" asp-route-id="@patternDetail.PatternDetailId" class="btn btn-primary">
                            <i class="fa fa-pencil-alt"></i>
                        </a>
                        <a asp-controller="PatternDetail" asp-action="Delete" asp-route-id="@patternDetail.PatternDetailId" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#patternDetail").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    }
                ],
                columnDefs: [
                    {
                        targets: 4,
                        orderable: false,
                        searchable: false
                    }
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json'
                }
            });
        });
    </script>
}